### ISSUE TITLE
Update question answer

### ISSUE THREAD

**Issue by Sedose** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Practice-Tests-Exams-Questions-Answers#19]
It seems like the question answer should be updated cause **Premier** plan is outdated.
Question:

> Your company plans to request an architectural review of an Azure environment from Microsoft. The company currently has a Basic support plan. You need to recommend a new support plan for the company. The solution must minimize costs. Which support plan should you recommend?

-  **Premier**.
-  Developer.
-  Professional Direct.
-  Standard.

**Comment by Sedose** [comment]
And it's hard for me to chose the answer. I searched the web but ...

**Comment by danieldanielecki** [comment]
@Sedose which answer would you recommend to put instead?

**Comment by danieldanielecki** [comment]
Also, what about other questions and answers referring to `Premier`?

**Comment by Sedose** [comment]
@danieldanielecki 
I'll probably try to investigate that a little bit later and try to ask my colleagues and respond. But looking into https://azure.microsoft.com/en-us/support/plans there is ARCHITECTURE SUPPORT: **General guidance** under [DEVELOPER, STANDARD] plans columns. 
It needs to be checked if **General guidance** includes **architectural review of an Azure environment from Microsoft**. If it is included than the answer is Developer because it's less expensive and includes ARCHITECTURE SUPPORT: General guidance. If not then PROFESSIONAL DIRECT cause it incudes **Guidance from a pool of ProDirect delivery managers**

**Comment by Sedose** [comment]
I think the answer PROFESSIONAL DIRECT

**Comment by danieldanielecki** [comment]
@Sedose keep me posted how to edit this/these questions related to `Premier`, till then - I'll keep this issue open!

**Comment by Sedose** [comment]
@danieldanielecki 

I truly don't have a clue what should be done in this case. I think the question should be deleted cause Microsoft retiring premier support plan. My colleagues also don't know)

**Comment by Sedose** [comment]
Or the question could be left. Cause it's a good question to explore and compare plans https://azure.microsoft.com/en-us/support/plans

**Comment by cabezon666** [comment]
Hello, nice to meet you all.
For what I understood, the solution should be : **Developer**, keeping the minimal budget cost.

**Comment by danieldanielecki** [comment]
https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Practice-Tests-Exams-Questions-Answers/commit/9a4b851e40b8d8a64ad561235b6d7bc633a25353. - how are the changes looking for you guys? EA is also obsolete.

**Comment by danieldanielecki** [comment]
https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Practice-Tests-Exams-Questions-Answers/commit/9a4b851e40b8d8a64ad561235b6d7bc633a25353. - how are the changes looking for you guys? EA is also obsolete.

**Comment by cabezon666** [comment]
> [9a4b851](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Practice-Tests-Exams-Questions-Answers/commit/9a4b851e40b8d8a64ad561235b6d7bc633a25353). - how are the changes looking for you guys? EA is also obsolete.

Yes, also I think is quite obsolete.

**Comment by Sedose** [comment]
> [9a4b851](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Practice-Tests-Exams-Questions-Answers/commit/9a4b851e40b8d8a64ad561235b6d7bc633a25353). - how are the changes looking for you guys? EA is also obsolete.

I added a comment for this commit navigating the link
