### ISSUE TITLE
why are these answers different?

### ISSUE THREAD

**Issue by fatkhanfauzi** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Practice-Tests-Exams-Questions-Answers#22]
Hi..

for question:
> You have an Azure environment. You need to create a new Azure virtual machine from a tablet that runs the Android operating system. Solution: You use Bash in Azure Cloud Shell. Does this meet the goal?

The answer is YES

but for question:
> You need to create a new Azure virtual machine from an Android laptop. Solution: You use Bash in Azure Cloud Shell. Does this meet the goal?

The answer is NO

I believe the answer for the last question above should be YES as well.

ref: https://learn.microsoft.com/en-us/azure/cloud-shell/overview

Thanks.

**Comment by danieldanielecki** [comment]
@fatkhanfauzi, do you know any Android laptop? ;-)

as we can find in https://www.quora.com/Why-arent-there-Android-laptops discussions, technically Android laptops exists, but in this question we assume a general knowledge. Hence, we assumed, nothing such as Android laptop exists (
